### ISSUE TITLE
KNN.CUDA

### ISSUE THREAD

**Issue by Wangyi1121** [xiaoyao3302/PoinTramba#6]
Hello author,

I hope you're doing well. I'm encountering an issue that seems to be related to KNN, but it's peculiar in that the error only occurs when I run the program in debug mode; it doesn't happen when I execute the program from the command line. Could you help me understand what might be causing this discrepancy?

Traceback (most recent call last):
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/media/q/a50d1d78-9e43-4e73-a116-cc66ab4b8064/PoinTramba-master/tools/__init__.py", line 2, in <module>
    from .runner import test_net
  File "/media/q/a50d1d78-9e43-4e73-a116-cc66ab4b8064/PoinTramba-master/tools/runner.py", line 5, in <module>
    from tools import builder
  File "/media/q/a50d1d78-9e43-4e73-a116-cc66ab4b8064/PoinTramba-master/tools/builder.py", line 8, in <module>
    from models import build_model_from_cfg
  File "/media/q/a50d1d78-9e43-4e73-a116-cc66ab4b8064/PoinTramba-master/models/__init__.py", line 1, in <module>
    from .point_mamba import PointMamba
  File "/media/q/a50d1d78-9e43-4e73-a116-cc66ab4b8064/PoinTramba-master/models/point_mamba.py", line 27, in <module>
    from knn_cuda import KNN
  File "/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/__init__.py", line 26, in load_cpp_ext
    ext = load(
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'knn': [1/3] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/TH -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/THC -isystem /home/q/anaconda3/envs/PoinTramba/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
FAILED: knn.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/TH -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/THC -isystem /home/q/anaconda3/envs/PoinTramba/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
nvcc fatal   : Value 'c++17' is not defined for option 'std'
[2/3] c++ -MMD -MF knn.o.d -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/TH -isystem /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/THC -isystem /home/q/anaconda3/envs/PoinTramba/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O2 -c /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp -o knn.o 
/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp: In function ‘std::vector<at::Tensor> knn(at::Tensor&, at::Tensor&, int)’:
/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:34:39: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     float * ref_dev = ref.data<float>();
                                       ^
In file included from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3:0,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:2:
/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:244:7: note: declared here
   T * data() const {
       ^~~~
/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:35:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     float * query_dev = query.data<float>();
                                           ^
In file included from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3:0,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:2:
/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:244:7: note: declared here
   T * data() const {
       ^~~~
/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:38:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     float * dist_dev = dist.data<float>();
                                         ^
In file included from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3:0,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:2:
/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:244:7: note: declared here
   T * data() const {
       ^~~~
/home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:39:37: warning: ‘T* at::Tensor::data() const [with T = long int]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. [-Wdeprecated-declarations]
     long * ind_dev = ind.data<long>();
                                     ^
In file included from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3:0,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/q/.local/lib/python3.9/site-packages/KNN_CUDA-0.2-py3.9.egg/knn_cuda/csrc/cuda/knn.cpp:2:
/home/q/anaconda3/envs/PoinTramba/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:244:7: note: declared here
   T * data() const {
       ^~~~
ninja: build stopped: subcommand failed.

**Comment by xiaoyao3302** [comment]
Hi, please use one single card for debug.
